# Book settings
title: OpenPifPaf Guide
author: Sven Kreiss
# logo: logo.png

# latex:
#   latex_documents:
#     targetname: book.tex

# Information about where the book exists on the web
repository:
  url                       : https://github.com/vita-epfl/openpifpaf  # Online location of your book
  book_path                 : guide  # Optional path to your book, relative to the repository root
  branch                    : guide  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
