# Book settings
title: OpenPifPaf Guide
author: Sven Kreiss
email: research@svenkreiss.com
logo: logo.png
discription: Guide for OpenPifPaf.

# latex:
#   latex_documents:
#     targetname: book.tex

html:
  favicon: favicon.png

# Information about where the book exists on the web
repository:
  url                       : https://github.com/vita-epfl/openpifpaf  # Online location of your book
  path_to_book              : guide  # Optional path to your book, relative to the repository root
  branch                    : stable  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url             : "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
